package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * Codebook generated by hbm2java
 */
public class Codebook implements java.io.Serializable {

	private int codebookId;
	private String coding;
	private int codeValue;
	private short lang;
	private String codeText;

	public Codebook() {
	}

	public Codebook(int codebookId, String coding, int codeValue, short lang,
			String codeText) {
		this.codebookId = codebookId;
		this.coding = coding;
		this.codeValue = codeValue;
		this.lang = lang;
		this.codeText = codeText;
	}

	public int getCodebookId() {
		return this.codebookId;
	}

	public void setCodebookId(int codebookId) {
		this.codebookId = codebookId;
	}

	public String getCoding() {
		return this.coding;
	}

	public void setCoding(String coding) {
		this.coding = coding;
	}

	public int getCodeValue() {
		return this.codeValue;
	}

	public void setCodeValue(int codeValue) {
		this.codeValue = codeValue;
	}

	public short getLang() {
		return this.lang;
	}

	public void setLang(short lang) {
		this.lang = lang;
	}

	public String getCodeText() {
		return this.codeText;
	}

	public void setCodeText(String codeText) {
		this.codeText = codeText;
	}

}
