package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * Endurance generated by hbm2java
 */
public class Endurance implements java.io.Serializable {

	private int rowId;
	private Workout workout;
	private TrainingProgramSequence trainingProgramSequence;
	private Double resistance;
	private Short heartRate;

	public Endurance() {
	}

	public Endurance(int rowId, Workout workout,
			TrainingProgramSequence trainingProgramSequence) {
		this.rowId = rowId;
		this.workout = workout;
		this.trainingProgramSequence = trainingProgramSequence;
	}

	public Endurance(int rowId, Workout workout,
			TrainingProgramSequence trainingProgramSequence, Double resistance,
			Short heartRate) {
		this.rowId = rowId;
		this.workout = workout;
		this.trainingProgramSequence = trainingProgramSequence;
		this.resistance = resistance;
		this.heartRate = heartRate;
	}

	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public Workout getWorkout() {
		return this.workout;
	}

	public void setWorkout(Workout workout) {
		this.workout = workout;
	}

	public TrainingProgramSequence getTrainingProgramSequence() {
		return this.trainingProgramSequence;
	}

	public void setTrainingProgramSequence(
			TrainingProgramSequence trainingProgramSequence) {
		this.trainingProgramSequence = trainingProgramSequence;
	}

	public Double getResistance() {
		return this.resistance;
	}

	public void setResistance(Double resistance) {
		this.resistance = resistance;
	}

	public Short getHeartRate() {
		return this.heartRate;
	}

	public void setHeartRate(Short heartRate) {
		this.heartRate = heartRate;
	}

}
