package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Fitness generated by hbm2java
 */
public class Fitness implements java.io.Serializable {

	private int rowId;
	private Workout workout;
	private TrainingProgramSequence trainingProgramSequence;
	private Double value;
	private Date trainingTime;
	private String note;

	public Fitness() {
	}

	public Fitness(int rowId, Workout workout,
			TrainingProgramSequence trainingProgramSequence) {
		this.rowId = rowId;
		this.workout = workout;
		this.trainingProgramSequence = trainingProgramSequence;
	}

	public Fitness(int rowId, Workout workout,
			TrainingProgramSequence trainingProgramSequence, Double value,
			Date trainingTime, String note) {
		this.rowId = rowId;
		this.workout = workout;
		this.trainingProgramSequence = trainingProgramSequence;
		this.value = value;
		this.trainingTime = trainingTime;
		this.note = note;
	}

	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public Workout getWorkout() {
		return this.workout;
	}

	public void setWorkout(Workout workout) {
		this.workout = workout;
	}

	public TrainingProgramSequence getTrainingProgramSequence() {
		return this.trainingProgramSequence;
	}

	public void setTrainingProgramSequence(
			TrainingProgramSequence trainingProgramSequence) {
		this.trainingProgramSequence = trainingProgramSequence;
	}

	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

	public Date getTrainingTime() {
		return this.trainingTime;
	}

	public void setTrainingTime(Date trainingTime) {
		this.trainingTime = trainingTime;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
