package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PeriodCard generated by hbm2java
 */
public class PeriodCard implements java.io.Serializable {

	private int periodCardId;
	private Period period;
	private String name;
	private short sequence;
	private Set periodCardPrograms = new HashSet(0);
	private Set workoutCards = new HashSet(0);

	public PeriodCard() {
	}

	public PeriodCard(int periodCardId, Period period, String name,
			short sequence) {
		this.periodCardId = periodCardId;
		this.period = period;
		this.name = name;
		this.sequence = sequence;
	}

	public PeriodCard(int periodCardId, Period period, String name,
			short sequence, Set periodCardPrograms, Set workoutCards) {
		this.periodCardId = periodCardId;
		this.period = period;
		this.name = name;
		this.sequence = sequence;
		this.periodCardPrograms = periodCardPrograms;
		this.workoutCards = workoutCards;
	}

	public int getPeriodCardId() {
		return this.periodCardId;
	}

	public void setPeriodCardId(int periodCardId) {
		this.periodCardId = periodCardId;
	}

	public Period getPeriod() {
		return this.period;
	}

	public void setPeriod(Period period) {
		this.period = period;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public short getSequence() {
		return this.sequence;
	}

	public void setSequence(short sequence) {
		this.sequence = sequence;
	}

	public Set getPeriodCardPrograms() {
		return this.periodCardPrograms;
	}

	public void setPeriodCardPrograms(Set periodCardPrograms) {
		this.periodCardPrograms = periodCardPrograms;
	}

	public Set getWorkoutCards() {
		return this.workoutCards;
	}

	public void setWorkoutCards(Set workoutCards) {
		this.workoutCards = workoutCards;
	}

}
