package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * PeriodCardProgram generated by hbm2java
 */
public class PeriodCardProgram implements java.io.Serializable {

	private int rowId;
	private TrainingProgram trainingProgram;
	private PeriodCard periodCard;

	public PeriodCardProgram() {
	}

	public PeriodCardProgram(int rowId, TrainingProgram trainingProgram,
			PeriodCard periodCard) {
		this.rowId = rowId;
		this.trainingProgram = trainingProgram;
		this.periodCard = periodCard;
	}

	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public TrainingProgram getTrainingProgram() {
		return this.trainingProgram;
	}

	public void setTrainingProgram(TrainingProgram trainingProgram) {
		this.trainingProgram = trainingProgram;
	}

	public PeriodCard getPeriodCard() {
		return this.periodCard;
	}

	public void setPeriodCard(PeriodCard periodCard) {
		this.periodCard = periodCard;
	}

}
