package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Period generated by hbm2java
 */
public class Period implements java.io.Serializable {

	private int periodId;
	private String name;
	private Set periodTrainingPrograms = new HashSet(0);
	private Set periodEvents = new HashSet(0);
	private Set periodCards = new HashSet(0);

	public Period() {
	}

	public Period(int periodId, String name) {
		this.periodId = periodId;
		this.name = name;
	}

	public Period(int periodId, String name, Set periodTrainingPrograms,
			Set periodEvents, Set periodCards) {
		this.periodId = periodId;
		this.name = name;
		this.periodTrainingPrograms = periodTrainingPrograms;
		this.periodEvents = periodEvents;
		this.periodCards = periodCards;
	}

	public int getPeriodId() {
		return this.periodId;
	}

	public void setPeriodId(int periodId) {
		this.periodId = periodId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getPeriodTrainingPrograms() {
		return this.periodTrainingPrograms;
	}

	public void setPeriodTrainingPrograms(Set periodTrainingPrograms) {
		this.periodTrainingPrograms = periodTrainingPrograms;
	}

	public Set getPeriodEvents() {
		return this.periodEvents;
	}

	public void setPeriodEvents(Set periodEvents) {
		this.periodEvents = periodEvents;
	}

	public Set getPeriodCards() {
		return this.periodCards;
	}

	public void setPeriodCards(Set periodCards) {
		this.periodCards = periodCards;
	}

}
