package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * PeriodTrainingProgram generated by hbm2java
 */
public class PeriodTrainingProgram implements java.io.Serializable {

	private int rowId;
	private TrainingProgram trainingProgram;
	private Period period;

	public PeriodTrainingProgram() {
	}

	public PeriodTrainingProgram(int rowId, TrainingProgram trainingProgram,
			Period period) {
		this.rowId = rowId;
		this.trainingProgram = trainingProgram;
		this.period = period;
	}

	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public TrainingProgram getTrainingProgram() {
		return this.trainingProgram;
	}

	public void setTrainingProgram(TrainingProgram trainingProgram) {
		this.trainingProgram = trainingProgram;
	}

	public Period getPeriod() {
		return this.period;
	}

	public void setPeriod(Period period) {
		this.period = period;
	}

}
