package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PersonAddress generated by hbm2java
 */
public class PersonAddress implements java.io.Serializable {

	private int rowId;
	private Person person;
	private Date since;
	private String street;
	private String zip;
	private String city;
	private String country;

	public PersonAddress() {
	}

	public PersonAddress(int rowId, Person person, Date since, String street,
			String zip, String city, String country) {
		this.rowId = rowId;
		this.person = person;
		this.since = since;
		this.street = street;
		this.zip = zip;
		this.city = city;
		this.country = country;
	}

	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Date getSince() {
		return this.since;
	}

	public void setSince(Date since) {
		this.since = since;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
