package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PersonPhone generated by hbm2java
 */
public class PersonPhone implements java.io.Serializable {

	private int rowId;
	private Person person;
	private Date since;
	private short phoneType;
	private String phoneNumber;

	public PersonPhone() {
	}

	public PersonPhone(int rowId, Person person, Date since, short phoneType,
			String phoneNumber) {
		this.rowId = rowId;
		this.person = person;
		this.since = since;
		this.phoneType = phoneType;
		this.phoneNumber = phoneNumber;
	}

	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Date getSince() {
		return this.since;
	}

	public void setSince(Date since) {
		this.since = since;
	}

	public short getPhoneType() {
		return this.phoneType;
	}

	public void setPhoneType(short phoneType) {
		this.phoneType = phoneType;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

}
