package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * PersonalTrainerClient generated by hbm2java
 */
public class PersonalTrainerClient implements java.io.Serializable {

	private int rowId;
	private Person personByTrainerId;
	private Person personByPersonId;
	private short status;

	public PersonalTrainerClient() {
	}

	public PersonalTrainerClient(int rowId, Person personByTrainerId,
			Person personByPersonId, short status) {
		this.rowId = rowId;
		this.personByTrainerId = personByTrainerId;
		this.personByPersonId = personByPersonId;
		this.status = status;
	}

	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public Person getPersonByTrainerId() {
		return this.personByTrainerId;
	}

	public void setPersonByTrainerId(Person personByTrainerId) {
		this.personByTrainerId = personByTrainerId;
	}

	public Person getPersonByPersonId() {
		return this.personByPersonId;
	}

	public void setPersonByPersonId(Person personByPersonId) {
		this.personByPersonId = personByPersonId;
	}

	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

}
