package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PersonEmail generated by hbm2java
 */
public class PersonEmail implements java.io.Serializable {

	private int rowId;
	private Person person;
	private Date since;
	private short emailType;
	private String emailAddress;

	public PersonEmail() {
	}

	public PersonEmail(int rowId, Person person, Date since, short emailType,
			String emailAddress) {
		this.rowId = rowId;
		this.person = person;
		this.since = since;
		this.emailType = emailType;
		this.emailAddress = emailAddress;
	}

	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Date getSince() {
		return this.since;
	}

	public void setSince(Date since) {
		this.since = since;
	}

	public short getEmailType() {
		return this.emailType;
	}

	public void setEmailType(short emailType) {
		this.emailType = emailType;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

}
