package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PersonIdentification generated by hbm2java
 */
public class PersonIdentification implements java.io.Serializable {

	private int rowId;
	private Person person;
	private Date since;
	private Date dateOfBirth;
	private short nationality;

	public PersonIdentification() {
	}

	public PersonIdentification(int rowId, Person person, Date since,
			Date dateOfBirth, short nationality) {
		this.rowId = rowId;
		this.person = person;
		this.since = since;
		this.dateOfBirth = dateOfBirth;
		this.nationality = nationality;
	}

	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Date getSince() {
		return this.since;
	}

	public void setSince(Date since) {
		this.since = since;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public short getNationality() {
		return this.nationality;
	}

	public void setNationality(short nationality) {
		this.nationality = nationality;
	}

}
