package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * Power generated by hbm2java
 */
public class Power implements java.io.Serializable {

	private int rowId;
	private Workout workout;
	private TrainingProgramSequence trainingProgramSequence;
	private Double value;

	public Power() {
	}

	public Power(int rowId, Workout workout,
			TrainingProgramSequence trainingProgramSequence) {
		this.rowId = rowId;
		this.workout = workout;
		this.trainingProgramSequence = trainingProgramSequence;
	}

	public Power(int rowId, Workout workout,
			TrainingProgramSequence trainingProgramSequence, Double value) {
		this.rowId = rowId;
		this.workout = workout;
		this.trainingProgramSequence = trainingProgramSequence;
		this.value = value;
	}

	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public Workout getWorkout() {
		return this.workout;
	}

	public void setWorkout(Workout workout) {
		this.workout = workout;
	}

	public TrainingProgramSequence getTrainingProgramSequence() {
		return this.trainingProgramSequence;
	}

	public void setTrainingProgramSequence(
			TrainingProgramSequence trainingProgramSequence) {
		this.trainingProgramSequence = trainingProgramSequence;
	}

	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

}
