package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TrainingProgram generated by hbm2java
 */
public class TrainingProgram implements java.io.Serializable {

	private int programId;
	private short programType;
	private String name;
	private String description;
	private Short exerciseCount;
	private Set trainingProgramSequences = new HashSet(0);
	private Set periodTrainingPrograms = new HashSet(0);
	private Set periodCardPrograms = new HashSet(0);

	public TrainingProgram() {
	}

	public TrainingProgram(int programId, short programType, String name,
			String description) {
		this.programId = programId;
		this.programType = programType;
		this.name = name;
		this.description = description;
	}

	public TrainingProgram(int programId, short programType, String name,
			String description, Short exerciseCount,
			Set trainingProgramSequences, Set periodTrainingPrograms,
			Set periodCardPrograms) {
		this.programId = programId;
		this.programType = programType;
		this.name = name;
		this.description = description;
		this.exerciseCount = exerciseCount;
		this.trainingProgramSequences = trainingProgramSequences;
		this.periodTrainingPrograms = periodTrainingPrograms;
		this.periodCardPrograms = periodCardPrograms;
	}

	public int getProgramId() {
		return this.programId;
	}

	public void setProgramId(int programId) {
		this.programId = programId;
	}

	public short getProgramType() {
		return this.programType;
	}

	public void setProgramType(short programType) {
		this.programType = programType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Short getExerciseCount() {
		return this.exerciseCount;
	}

	public void setExerciseCount(Short exerciseCount) {
		this.exerciseCount = exerciseCount;
	}

	public Set getTrainingProgramSequences() {
		return this.trainingProgramSequences;
	}

	public void setTrainingProgramSequences(Set trainingProgramSequences) {
		this.trainingProgramSequences = trainingProgramSequences;
	}

	public Set getPeriodTrainingPrograms() {
		return this.periodTrainingPrograms;
	}

	public void setPeriodTrainingPrograms(Set periodTrainingPrograms) {
		this.periodTrainingPrograms = periodTrainingPrograms;
	}

	public Set getPeriodCardPrograms() {
		return this.periodCardPrograms;
	}

	public void setPeriodCardPrograms(Set periodCardPrograms) {
		this.periodCardPrograms = periodCardPrograms;
	}

}
