package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * WorkoutCard generated by hbm2java
 */
public class WorkoutCard implements java.io.Serializable {

	private int cardId;
	private PeriodCard periodCard;
	private Person person;
	private Set workouts = new HashSet(0);

	public WorkoutCard() {
	}

	public WorkoutCard(int cardId, PeriodCard periodCard, Person person) {
		this.cardId = cardId;
		this.periodCard = periodCard;
		this.person = person;
	}

	public WorkoutCard(int cardId, PeriodCard periodCard, Person person,
			Set workouts) {
		this.cardId = cardId;
		this.periodCard = periodCard;
		this.person = person;
		this.workouts = workouts;
	}

	public int getCardId() {
		return this.cardId;
	}

	public void setCardId(int cardId) {
		this.cardId = cardId;
	}

	public PeriodCard getPeriodCard() {
		return this.periodCard;
	}

	public void setPeriodCard(PeriodCard periodCard) {
		this.periodCard = periodCard;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Set getWorkouts() {
		return this.workouts;
	}

	public void setWorkouts(Set workouts) {
		this.workouts = workouts;
	}

}
