package fi.xmethod.crm_db;

// Generated Feb 20, 2014 8:20:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Workout generated by hbm2java
 */
public class Workout implements java.io.Serializable {

	private int workoutId;
	private WorkoutCard workoutCard;
	private Date trainingDate;
	private short exerciseSequence;
	private Set fitnesses = new HashSet(0);
	private Set powers = new HashSet(0);
	private Set endurances = new HashSet(0);

	public Workout() {
	}

	public Workout(int workoutId, WorkoutCard workoutCard, Date trainingDate,
			short exerciseSequence) {
		this.workoutId = workoutId;
		this.workoutCard = workoutCard;
		this.trainingDate = trainingDate;
		this.exerciseSequence = exerciseSequence;
	}

	public Workout(int workoutId, WorkoutCard workoutCard, Date trainingDate,
			short exerciseSequence, Set fitnesses, Set powers, Set endurances) {
		this.workoutId = workoutId;
		this.workoutCard = workoutCard;
		this.trainingDate = trainingDate;
		this.exerciseSequence = exerciseSequence;
		this.fitnesses = fitnesses;
		this.powers = powers;
		this.endurances = endurances;
	}

	public int getWorkoutId() {
		return this.workoutId;
	}

	public void setWorkoutId(int workoutId) {
		this.workoutId = workoutId;
	}

	public WorkoutCard getWorkoutCard() {
		return this.workoutCard;
	}

	public void setWorkoutCard(WorkoutCard workoutCard) {
		this.workoutCard = workoutCard;
	}

	public Date getTrainingDate() {
		return this.trainingDate;
	}

	public void setTrainingDate(Date trainingDate) {
		this.trainingDate = trainingDate;
	}

	public short getExerciseSequence() {
		return this.exerciseSequence;
	}

	public void setExerciseSequence(short exerciseSequence) {
		this.exerciseSequence = exerciseSequence;
	}

	public Set getFitnesses() {
		return this.fitnesses;
	}

	public void setFitnesses(Set fitnesses) {
		this.fitnesses = fitnesses;
	}

	public Set getPowers() {
		return this.powers;
	}

	public void setPowers(Set powers) {
		this.powers = powers;
	}

	public Set getEndurances() {
		return this.endurances;
	}

	public void setEndurances(Set endurances) {
		this.endurances = endurances;
	}

}
